### ISSUE TITLE
请问还维护么？部署完成以后遇到几个问题，想请教一下。

### ISSUE THREAD

**Issue by littleheary** [0kami/MonitorServer#1]
1、打开Laravel development server或者是直接访问"/public/index.php"都会出现报错，是关于数据库中用户重复那里的报错，但是我看数据库就之前初始化时候的那一个用户。我看语句，似乎是又要insert，这个是不是bug呀？
![image](https://user-images.githubusercontent.com/26987382/74466535-5dadee80-4ed2-11ea-885b-9e7527a4ea6b.png)
2、在后台点击“monitor”的“task”和“message”也都会报错，提示说找不到“monitor.tasks”，这个是不是因为缺少模块呀？
![image](https://user-images.githubusercontent.com/26987382/74466612-87ffac00-4ed2-11ea-9c37-4a0657a9f1fc.png)

**Comment by littleheary** [comment]
sql唯一约束的那个，我把索引的unique改成normal了，现在是不报错了，不知道会不会对后续造成影响。
monitor/task缺少视图的那个，是确实没有，还是我配置有问题呀？

**Comment by wh1t3p1g** [comment]
你好，这个项目当初是毕设的成果，已经不维护了。
当时上传时测试过，可能版本上有区别，不建议再使用这个应用。
你可以参考Client端的主要代码，主要的技术创新在于客户端的处理。
服务端如果你想用的话，可以自己改改，祝好XD

**Comment by littleheary** [comment]
请问，客户端和服务端通信的端口是多少？我似乎没找到通信端口，几个已开放端口也试了一下，都不行。

**Comment by wh1t3p1g** [comment]
通信端口只要配置好Client端，Client端会主动去请求Server端

**Comment by littleheary** [comment]
![image](https://user-images.githubusercontent.com/26987382/74509036-81f1e580-4f3b-11ea-952a-23b45a5a9e72.png)
你看，客户端我是这么配置的，最后启动客户端会提示无法与服务端连接。换其他端口也是一样

**Comment by wh1t3p1g** [comment]
额，你调调看吧。几年前的东西了细节已经忘记了

**Comment by littleheary** [comment]
嗯嗯，谢谢回复
